1466 upgrate torchio and itk version to fix install error (#1467)
Fixes #1466 

### Description
Upgrate torchio version to fix install error.
Also update itk version since this error.
```
ERROR: Could not find a version that satisfies the requirement itk==5.1.0 (from versions: 4.12.0.post1, 4.13.0, 4.13.1.post1, 5.0a1, 5.0a2, 5.0b1, 5.0b3, 5.0rc1, 5.0rc2, 5.0.0, 5.0.0.post1, 5.0.1, 5.3rc2, 5.3rc2.post1, 5.3rc3, 5.3rc4, 5.3rc4.post1, 5.3rc4.post2, 5.3rc4.post3, 5.3rc4.post4, 5.3.0, 5.4rc1)
ERROR: No matching distribution found for itk==5.1.0
```

### Checks
<!--- Put an `x` in all the boxes that apply, and remove the not
applicable items -->
- [ ] Avoid including large-size files in the PR.
- [ ] Clean up long text outputs from code cells in the notebook.
- [ ] For security purposes, please check the contents and remove any
sensitive info such as user names and private key.
- [ ] Ensure (1) hyperlinks and markdown anchors are working (2) use
relative paths for tutorial repo files (3) put figure and graphs in the
`./figure` folder
- [ ] Notebook runs automatically `./runner.sh -t <path to .ipynb file>`

Signed-off-by: KumoLiu <yunl@nvidia.com>